-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZo83WVHiesfQ7mhX
sPQD03W9rRByj1ETTQWNBtTR/Y+gCgYIKoZIzj0DAQehRANCAATbb9GHqAHrVtap
Ubdkj6lr7ivRy4iWszaWzq/CXjY6Mm7RhkhJpYplS2HE1kPHqlcERILbvjrMWIVD
JWYh3X69
-----END PRIVATE KEY-----